# Generated by Django 4.2.8 on 2025-02-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=150, verbose_name="닉네임"),
        ),
    ]
