# Generated by Django 4.2.8 on 2025-02-14 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='닉네임'),
        ),
    ]
